name: YaSpeller

on:
  push:
    branches:
      - new

jobs:
  yaspeller:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "17.x"
      - name: Проверка правописания
        run: npx yaspeller .